name: Github Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Git config
        run: |
          git config --global user.email "hbnation.it@gmail.com"
          git config --global user.name "hibernationit"

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        run: |
          yarn deploy